/**
 * Builds web-ready images from apps/web/assets-src (DESIGN section 9):
 * voxel WebP at 128/256 px, the transparent logo and mark, and PWA icons.
 * Deterministic: same sources produce the same files. Run: bun run --cwd apps/web assets
 */
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { basename, join } from "node:path";
import sharp from "sharp";

const root = join(import.meta.dir, "..");
const src = join(root, "assets-src");
const voxelOut = join(root, "src/assets/voxels");
const brandOut = join(root, "src/assets/brand");
const iconOut = join(root, "public/icons");
const paper = "#FDFBF4";
const transparent = { r: 0, g: 0, b: 0, alpha: 0 };

async function voxels(): Promise<string[]> {
  await rm(voxelOut, { recursive: true, force: true });
  await mkdir(voxelOut, { recursive: true });
  const files = (await readdir(join(src, "voxels"))).filter((f) => f.endsWith(".png")).sort();
  const names: string[] = [];
  for (const file of files) {
    const name = basename(file, ".png");
    const trimmed = await sharp(join(src, "voxels", file))
      .trim()
      .toBuffer();
    for (const size of [128, 256]) {
      await sharp(trimmed)
        .resize(size, size, { fit: "contain", background: transparent })
        .webp({ quality: 82, alphaQuality: 90, effort: 6 })
        .toFile(join(voxelOut, `${name}-${size}.webp`));
    }
    names.push(name);
  }
  const list = names.map((n) => `  "${n}",`).join("\n");
  await writeFile(
    join(voxelOut, "names.ts"),
    `// Generated by scripts/build-assets.ts. Do not edit.\nexport const voxelNames = [\n${list}\n] as const;\n\nexport type VoxelName = (typeof voxelNames)[number];\n`,
  );
  return names;
}

async function brand(): Promise<void> {
  await mkdir(brandOut, { recursive: true });
  await mkdir(iconOut, { recursive: true });
  const logo = await sharp(join(src, "brand/sayso-logo-transparent.png")).trim().toBuffer();
  await sharp(logo)
    .resize({ height: 160 })
    .webp({ quality: 90, alphaQuality: 100, effort: 6 })
    .toFile(join(brandOut, "logo.webp"));
  const mark = await sharp(join(src, "brand/sayso-icon.png")).trim().toBuffer();
  await sharp(mark)
    .resize(256, 256, { fit: "contain", background: transparent })
    .webp({ quality: 90, alphaQuality: 100, effort: 6 })
    .toFile(join(brandOut, "mark.webp"));

  // App icons: the mark on paper. Maskable keeps the mark inside the 80 % safe zone.
  const icon = async (size: number, inset: number, file: string) => {
    const inner = Math.round(size * (1 - 2 * inset));
    const art = await sharp(mark)
      .resize(inner, inner, { fit: "contain", background: transparent })
      .toBuffer();
    await sharp({ create: { width: size, height: size, channels: 4, background: paper } })
      .composite([{ input: art, gravity: "center" }])
      .png({ compressionLevel: 9 })
      .toFile(join(iconOut, file));
  };
  await icon(192, 0.1, "icon-192.png");
  await icon(512, 0.1, "icon-512.png");
  await icon(512, 0.2, "icon-maskable-512.png");
  await icon(180, 0.12, "apple-touch-icon.png");
}

const names = await voxels();
await brand();
console.log(`voxels: ${names.length} x 2 sizes; brand: logo, mark; icons: 4`);
