/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as DesignRouteImport } from './routes/design'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as Design3dRouteImport } from './routes/design_.3d'
import { Route as DesignPlayerRouteImport } from './routes/design_.player'
import { Route as DesignRecordsRouteImport } from './routes/design_.records'
import { Route as EpisodeIdRouteImport } from './routes/episode.$id'
import { Route as ResultsIdRouteImport } from './routes/results.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const Design3dRoute = Design3dRouteImport.update({
  id: '/design_/3d',
  path: '/design/3d',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignPlayerRoute = DesignPlayerRouteImport.update({
  id: '/design_/player',
  path: '/design/player',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRecordsRoute = DesignRecordsRouteImport.update({
  id: '/design_/records',
  path: '/design/records',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodeIdRoute = EpisodeIdRouteImport.update({
  id: '/episode/$id',
  path: '/episode/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIdRoute = ResultsIdRouteImport.update({
  id: '/results/$id',
  path: '/results/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/arena': typeof ArenaRoute
  '/design': typeof DesignRoute
  '/join': typeof JoinRoute
  '/leaderboard': typeof LeaderboardRoute
  '/portfolio': typeof PortfolioRoute
  '/design/3d': typeof Design3dRoute
  '/design/player': typeof DesignPlayerRoute
  '/design/records': typeof DesignRecordsRoute
  '/episode/$id': typeof EpisodeIdRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/arena': typeof ArenaRoute
  '/design': typeof DesignRoute
  '/join': typeof JoinRoute
  '/leaderboard': typeof LeaderboardRoute
  '/portfolio': typeof PortfolioRoute
  '/design/3d': typeof Design3dRoute
  '/design/player': typeof DesignPlayerRoute
  '/design/records': typeof DesignRecordsRoute
  '/episode/$id': typeof EpisodeIdRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/arena': typeof ArenaRoute
  '/design': typeof DesignRoute
  '/join': typeof JoinRoute
  '/leaderboard': typeof LeaderboardRoute
  '/portfolio': typeof PortfolioRoute
  '/design_/3d': typeof Design3dRoute
  '/design_/player': typeof DesignPlayerRoute
  '/design_/records': typeof DesignRecordsRoute
  '/episode/$id': typeof EpisodeIdRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/arena'
    | '/design'
    | '/join'
    | '/leaderboard'
    | '/portfolio'
    | '/design/3d'
    | '/design/player'
    | '/design/records'
    | '/episode/$id'
    | '/results/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/arena'
    | '/design'
    | '/join'
    | '/leaderboard'
    | '/portfolio'
    | '/design/3d'
    | '/design/player'
    | '/design/records'
    | '/episode/$id'
    | '/results/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/arena'
    | '/design'
    | '/join'
    | '/leaderboard'
    | '/portfolio'
    | '/design_/3d'
    | '/design_/player'
    | '/design_/records'
    | '/episode/$id'
    | '/results/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ArenaRoute: typeof ArenaRoute
  DesignRoute: typeof DesignRoute
  JoinRoute: typeof JoinRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PortfolioRoute: typeof PortfolioRoute
  Design3dRoute: typeof Design3dRoute
  DesignPlayerRoute: typeof DesignPlayerRoute
  DesignRecordsRoute: typeof DesignRecordsRoute
  EpisodeIdRoute: typeof EpisodeIdRoute
  ResultsIdRoute: typeof ResultsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design_/3d': {
      id: '/design_/3d'
      path: '/design/3d'
      fullPath: '/design/3d'
      preLoaderRoute: typeof Design3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design_/player': {
      id: '/design_/player'
      path: '/design/player'
      fullPath: '/design/player'
      preLoaderRoute: typeof DesignPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design_/records': {
      id: '/design_/records'
      path: '/design/records'
      fullPath: '/design/records'
      preLoaderRoute: typeof DesignRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episode/$id': {
      id: '/episode/$id'
      path: '/episode/$id'
      fullPath: '/episode/$id'
      preLoaderRoute: typeof EpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$id': {
      id: '/results/$id'
      path: '/results/$id'
      fullPath: '/results/$id'
      preLoaderRoute: typeof ResultsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ArenaRoute: ArenaRoute,
  DesignRoute: DesignRoute,
  JoinRoute: JoinRoute,
  LeaderboardRoute: LeaderboardRoute,
  PortfolioRoute: PortfolioRoute,
  Design3dRoute: Design3dRoute,
  DesignPlayerRoute: DesignPlayerRoute,
  DesignRecordsRoute: DesignRecordsRoute,
  EpisodeIdRoute: EpisodeIdRoute,
  ResultsIdRoute: ResultsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
