// Regenerates packages/core/abi/sayso.ts from Foundry artifacts so web, studio, CRE and the
// indexer share one ABI. Run `forge build` in contracts/ first.
// Usage: bun packages/core/scripts/export-sayso-abi.ts [--check]
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const outDir = join(import.meta.dir, "..", "..", "..", "contracts", "out");
const target = join(import.meta.dir, "..", "abi", "sayso.ts");
const contracts = [
  ["saysoMarketsAbi", "SaysoMarkets"],
  ["outcomeTokenAbi", "OutcomeToken"],
] as const;

const lines = [
  "// Generated by packages/core/scripts/export-sayso-abi.ts from contracts/out (forge build).",
  "// Do not edit by hand; rerun the script after any contract interface change.",
  "",
];
for (const [name, contract] of contracts) {
  const artifact = JSON.parse(
    readFileSync(join(outDir, `${contract}.sol`, `${contract}.json`), "utf8"),
  ) as { abi: unknown[] };
  lines.push(`export const ${name} = ${JSON.stringify(artifact.abi, null, 2)} as const;`, "");
}
const generated = lines.join("\n");

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(target, "utf8");
  } catch {
    // Missing file is reported as drift below.
  }
  if (current !== generated) {
    console.error("abi/sayso.ts is stale: run forge build, then this script without --check");
    process.exit(1);
  }
  console.log("abi/sayso.ts matches the Foundry artifacts");
} else {
  writeFileSync(target, generated);
  console.log(`wrote ${target}`);
}
