// Regenerates packages/core/abi/kuru.ts from an unpacked @kuru-labs/kuru-sdk tarball.
// Usage: bun packages/core/scripts/vendor-kuru-abi.ts <path-to-unpacked>/package
// Only the ABI arrays are kept; the SDK itself is never a dependency (it pulls in ethers v5).
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const pkgDir = process.argv[2];
if (!pkgDir) throw new Error("usage: vendor-kuru-abi.ts <unpacked kuru-sdk package dir>");

const pkg = JSON.parse(readFileSync(join(pkgDir, "package.json"), "utf8")) as { version: string };
const files = [
  ["orderBookAbi", "OrderBook"],
  ["routerAbi", "Router"],
  ["marginAccountAbi", "MarginAccount"],
] as const;

const out = [
  `// Generated by packages/core/scripts/vendor-kuru-abi.ts from @kuru-labs/kuru-sdk@${pkg.version}.`,
  "// Do not edit by hand; see packages/core/abi/SOURCE.md.",
  "",
];
for (const [name, file] of files) {
  const artifact = JSON.parse(readFileSync(join(pkgDir, "abi", `${file}.json`), "utf8")) as {
    abi: unknown[];
  };
  out.push(`export const ${name} = ${JSON.stringify(artifact.abi, null, 2)} as const;`, "");
}
writeFileSync(join(import.meta.dir, "..", "abi", "kuru.ts"), out.join("\n"));
